# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pr:
- master

jobs:
- job: tbss
  timeoutInMinutes: 120

  pool:
    vmImage: 'ubuntu-latest'

  variables:
    dockerId: tbillah
    imageName: tbillah/entry_point
    imageTag: 0.1
    user: tb571
    wd: /home


  steps:
  - task: Docker@2
    displayName: Login to Docker Hub
    inputs:
      command: login
      containerRegistry: dockerHub


  - script: |
        docker build -t $(imageName) -f Dockerfile.entrypoint --build-arg USER=$(user) --build-arg CWD=$(wd) .
        docker run --rm $(imageName) "python -V"
        # docker push $(imageName)
    displayName: 'Build and test a docker image'
    failOnStderr: true

  
  - task: Docker@2
    displayName: push
    inputs:
      command: push
      repository: $(imageName)
      tags: $(imageTag)

